Qaqc issue 79
NREL/openstudio-common-measures-gem pull request #95
Opened 2022-04-25 15:35 UTC by DavidGoldwasser

I don't have any more changes planed for next measure gem release.

2022-04-26 17:10 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_eui_by_end_use.rb
> +      bt_cz = std.model_get_building_climate_zone_and_building_type(@model)
`model_get_building_climate_zone_and_building_type` no longer exists.  It's called `model_get_building_properties` now

2022-04-26 17:13 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_eui_reasonableness.rb
> +      if building_type.include?("Office") then building_type = "Office" end
building type enumerations

2022-04-26 17:13 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_eui_reasonableness.rb
> +      target_eui = std.model_find_target_eui(@model)
this won't work if the model doesn't have an enumerated building type set

2022-04-26 17:15 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_internal_loads.rb
> +      bt_cz = std.model_get_building_climate_zone_and_building_type(@model)
use `model_get_building_properties`

2022-04-26 17:16 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_schedules.rb
> +      bt_cz = std.model_get_building_climate_zone_and_building_type(@model)
use `model_get_building_properties`

2022-04-26 17:17 UTC, mdahlhausen commented on lib/measures/generic_qaqc/resources/check_schedules.rb
> +    bt_cz = std.model_get_building_climate_zone_and_building_type(@model)
use `model_get_building_properties`

2022-04-26 17:20 UTC, mdahlhausen requested changes
Most of it looks find.  In fixing the EUI lookups, I did change the `model_get_building_climate_zone_and_building_type` method to `model_get_building_properties` in openstudio-standards v0.2.16.  I'm guessing we are going to want to either 1) set OS 3.4 as the minimum version, or 2) initialize the `model_get_building_climate_zone_and_building_type` method in the resource file for this measure.  That's probably the best approach as there are many who still use OS v2.9 b/c of sketchup and app integration.

2022-04-27 19:59 UTC, DavidGoldwasser commented
@mdahlhausen I'll need to have version of the measure that works with OpenStudio 3.3 to go with URBANopt that will be released shortly. Another URBANopt for 3.4 will come out a little later.

2022-05-04 05:33 UTC, merged